spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vending
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.producer: DEBUG
# Kafka settings
kafka:
  bootstrap-servers: localhost:9092
  producer:
    retries: 1

mapstruct:
  unmappedTargetPolicy: IGNORE